name: Generating docs using doxygen

on:
  push:
    branches:
      - dev

jobs:
  gen_docs:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install doxygen
        run: sudo apt update -y && sudo apt install -y doxygen
      
      - name: Generate docs
        run: |
          mkdir -p docs/html
          doxygen docs/doxygen.conf

      - name: Setup gh-pages branch
        run: |
          git fetch origin gh-pages || true
          git checkout gh-pages || git checkout --orphan gh-pages
          git reset --hard

      - name: Commit and push docs
        run: |
          cp -R docs/html/* .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git diff --cached --quiet || git commit -m "Auto-generating docs"
          git push origin gh-pages -f
