name: generating docs

on: push

jobs:
  production-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo test
      - run: sudo apt update
      - run: sudo apt install clang